Metrics/LineLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Documentation:
  Enabled: false

Naming/FileName:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/Lambda:
  Enabled: false
